### PR TITLE
Updated for linter 2.0.0

### LINKED ISSUE #36: v1 API of linter no longer supported, breaks this package
`linter-write-good` does not work with [v2.3.0](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` because the v1 API support was removed.

A guide to updating to v2 can be found [here](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md)

Workaround: downgrade to v2.2.0 using `apm install linter@2.2.0`

### PR DESCRIPTION
**Pull request by davidlday**
Closes #36

### CODE REVIEW

**Comment by jeremyf** [comment]
What is the status on this being merged and released?

**Comment by davidlday** [comment]
@Arcanemagus - I have the same question as @jeremyf. Is there anything else I can do to help this along?

**Comment by Arcanemagus** [comment]
It looks good to me, since I sent in an approval review... unfortunately as this isn't under the AtomLinter organization that's all I can do here. We'll need to wait for @gepoch to merge this and release a version that includes these changes.

Unfortunately it doesn't look like they have been active on GitHub in several years so you _might_ be better off forking this. If you do go that route and want it placed under the AtomLinter organization so this isn't an issue in the future for it just let me know. The same goes for you @gepoch! If you want to transfer this to the AtomLinter organization so it can continue to be maintained just let me know!

**Comment by davidlday** [comment]
Thanks, @Arcanemagus! I'll give @gepoch a week to respond. If he doesn't, I'll fork it and work with you to put it under the AtomLinter org.

**Comment by gepoch** [comment]
Hey folks, sorry for the delay... I haven't been using Atom for a couple of years now, so I'm happy to transfer this over to the atom linter org. If you lemme know what I need to do, I'll take care of it!

**Comment by Arcanemagus** [comment]
Full article is here: [Migrating a repository](https://github.com/AtomLinter/Meta/wiki/Migrating-a-repository)

The tl;dr though is to transfer it to me and I'll get it moved into the organization 😉. Thanks!

**Comment by gepoch** [comment]
@Arcanemagus transfer request sent! Thanks for taking care of it!

**Comment by Arcanemagus** [comment]
Transferred to the organization, thanks!

**Comment by Arcanemagus** [comment]
@davidlday Let me know if you want to be added to the maintainers team for this repository, I'll be doing some cleanup and maintenance on it and getting a release published, but it would be great to have somebody that uses it 😉.

**Comment by davidlday** [comment]
@Arcanemagus Would love to help out as part of the maintainers team.

**Pull request merged**
